### ISSUE TITLE
go: github.com/coreos/go-systemd/v22@v22.3.2: Get "https://proxy.golang.org/github.com/coreos/go-systemd/v22/@v/v22.3.2.mod": dial tcp 172.217.160.113:443: i/o timeout

### ISSUE THREAD

**Issue by duhaijian** [5high/HassOS-Actions#3]
手动编译出错，按网上说的更改GO代理也没用
>>> os-agent 1.2.1 Patching
(cd /build/output/build/os-agent-1.2.1; /build/output/host/bin/go mod vendor)
go: github.com/coreos/go-systemd/v22@v22.3.2: Get "https://proxy.golang.org/github.com/coreos/go-systemd/v22/@v/v22.3.2.mod": dial tcp 172.217.160.113:443: i/o timeout
make[1]: *** [package/pkg-generic.mk:228: /build/output/build/os-agent-1.2.1/.stamp_patched] Error 1
make[1]: Leaving directory '/build/buildroot'
make: *** [Makefile:35: ova] Error 2

**Comment by 5high** [comment]
export GOPROXY=goproxy.io
